tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-primary": "#ffffff",
                "surface-container-highest": "#e1e3e4",
                "on-tertiary": "#ffffff",
                "on-primary-container": "#ffa092",
                secondary: "#5e5e5e",
                "on-tertiary-container": "#abb4ff",
                "tertiary-container": "#0029dc",
                "surface-variant": "#e1e3e4",
                background: "#f8f9fa",
                "surface-bright": "#f8f9fa",
                "on-secondary-fixed": "#1b1b1b",
                "on-primary-fixed-variant": "#930000",
                "on-error": "#ffffff",
                surface: "#f8f9fa",
                "outline-variant": "#e4beb8",
                "inverse-primary": "#ffb4a8",
                "on-background": "#191c1d",
                "surface-container-high": "#e7e8e9",
                "on-secondary-fixed-variant": "#474747",
                "error-container": "#ffdad6",
                "on-primary-fixed": "#410000",
                "secondary-container": "#e2e2e2",
                "primary-container": "#990000",
                "on-surface": "#191c1d",
                tertiary: "#001ba0",
                "tertiary-fixed": "#dfe0ff",
                "surface-container-lowest": "#ffffff",
                "inverse-surface": "#2e3132",
                "inverse-on-surface": "#f0f1f2",
                "primary-fixed-dim": "#ffb4a8",
                "on-tertiary-fixed": "#000c61",
                error: "#ba1a1a",
                "on-surface-variant": "#5b403c",
                "surface-tint": "#b82014",
                "secondary-fixed-dim": "#c6c6c6",
                "on-secondary-container": "#646464",
                primary: "#2b7fff",
                "on-secondary": "#ffffff",
                "secondary-fixed": "#e2e2e2",
                outline: "#8f706b",
                "tertiary-fixed-dim": "#bcc2ff",
                "on-error-container": "#93000a",
                "surface-container": "#edeeef",
                "surface-container-low": "#f3f4f5",
                "primary-fixed": "#ffdad4",
                "surface-dim": "#d9dadb",
                "on-tertiary-fixed-variant": "#0027d4",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                "margin-desktop": "2rem",
                gutter: "1.5rem",
                "container-max-width": "1320px",
                base: "8px",
                "margin-mobile": "1rem",
            },
            fontFamily: {
                "body-lg": ["Inter"],
                "body-sm": ["Inter"],
                "label-sm": ["Inter"],
                "headline-md": ["Inter"],
                "display-lg": ["Inter"],
                "headline-lg": ["Inter"],
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "body-md": ["Inter"],
            },
            fontSize: {
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
                "headline-md": [
                    "24px",
                    { lineHeight: "32px", fontWeight: "600" },
                ],
                "display-lg": [
                    "48px",
                    {
                        lineHeight: "56px",
                        letterSpacing: "-0.02em",
                        fontWeight: "700",
                    },
                ],
                "headline-lg": [
                    "32px",
                    {
                        lineHeight: "40px",
                        letterSpacing: "-0.01em",
                        fontWeight: "600",
                    },
                ],
                "label-md": [
                    "14px",
                    {
                        lineHeight: "16px",
                        letterSpacing: "0.05em",
                        fontWeight: "600",
                    },
                ],
                "headline-lg-mobile": [
                    "28px",
                    { lineHeight: "36px", fontWeight: "600" },
                ],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
            },
        },
    },
};